version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk17
    commands:
      - echo Installing dependencies...
      - mvn clean install
  build:
    commands:
      - echo Building application...
      - mvn package
      - cp target/*.war app.war
  post_build:
    commands:
      - echo Uploading artifacts to S3...
      - aws s3 cp app.war s3://maven-web-app-artifacts/app.war
artifacts:
  files:
    - app.war
